[package]
name = "norse-audir"
version = "0.1.0"
authors = ["msiglreith <m.siglreith@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = { version = "0.3", features = ["debug", "ksmedia", "audioclient", "combaseapi", "coml2api", "devpkey", "mmdeviceapi", "objbase", "unknwnbase", "winerror", "synchapi"] }
